version: '3'

tasks:
  install-deps-ts:
    sources:
      - 'package.json'
      - 'package-lock.json'
    cmds:
      - npm i

  install-deps-gleam:
    sources:
      - 'gleam.toml'
    cmds:
      - gleam deps download

  install-deps:
    deps: [install-deps-ts, install-deps-gleam]

  build:
    deps: [install-deps]
    sources:
      - 'src/**/*.gleam'
      - 'ts/*.ts'
    generates:
      - 'build/dev/javascript/**/*'
    cmds:
      - gleam build
      - npx vite build
      - gleam build

  clean:
    - rm -rf build
    - rm src/*.mjs

  lint: npx biome lint

  format-check-ts: npx biome format
  format-check-gleam: gleam format --check
  format-check:
    deps: [format-check-ts, format-check-gleam]

  format-ts: npx biome format --write
  format-gleam: gleam format
  format:
    deps: [format-ts, format-gleam]

  test:
    deps: [build]
    cmd: gleam test --runtime nodejs

  docs: gleam docs build
